# Importing librabies

In [66]:
import pandas as pd
import numpy as np
import sklearn

# Reading the data

In [67]:
df = pd.read_csv("F:/mydata/Building_Permits.csv")
print(df.head())

  Permit Number  Permit Type            Permit Type Definition  \
0  201505065519            4                      sign - erect
1  201604195146            4                      sign - erect
2  201605278609            3  additions alterations or repairs
3  201611072166            8            otc alterations permit
4  201611283529            6                       demolitions

  Permit Creation Date Block  Lot  Street Number Street Number Suffix  \
0           05/06/2015  0326  023            140                  NaN
1           04/19/2016  0306  007            440                  NaN
2           05/27/2016  0595  203           1647                  NaN
3           11/07/2016  0156  011           1230                  NaN
4           11/28/2016  0342  001            950                  NaN

  Street Name Street Suffix      ...        Existing Construction Type  \
0       Ellis            St      ...                               3.0
1       Geary            St      ...                               3.0
2     Pacific            Av      ...                               1.0
3     Pacific            Av      ...                               5.0
4      Market            St      ...                               3.0

  Existing Construction Type Description Proposed Construction Type  \
0                          constr type 3                        NaN
1                          constr type 3                        NaN
2                          constr type 1                        1.0
3                         wood frame (5)                        5.0
4                          constr type 3                        NaN

  Proposed Construction Type Description Site Permit Supervisor District  \
0                                    NaN         NaN                 3.0
1                                    NaN         NaN                 3.0
2                          constr type 1         NaN                 3.0
3                         wood frame (5)         NaN                 3.0
4                                    NaN         NaN                 6.0

  Neighborhoods - Analysis Boundaries  Zipcode  \
0                          Tenderloin  94102.0
1                          Tenderloin  94102.0
2                        Russian Hill  94109.0
3                            Nob Hill  94109.0
4                          Tenderloin  94102.0

                                    Location      Record ID
0  (37.785719256680785, -122.40852313194863)  1380611233945
1   (37.78733980600732, -122.41063199757738)  1420164406718
2    (37.7946573324287, -122.42232562979227)  1424856504716
3   (37.79595867909168, -122.41557405519474)  1443574295566
4   (37.78315261897309, -122.40950883997789)   144548169992

[5 rows x 43 columns]

C:\Users\Radha\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (22,32) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

# Getting the number of missing values from each column

In [69]:
missing_values_count = df.isnull().sum()
missing_values_count[0:10]

Permit Number                  0
Permit Type                    0
Permit Type Definition         0
Permit Creation Date           0
Block                          0
Lot                            0
Street Number                  0
Street Number Suffix      196684
Street Name                    0
Street Suffix               2768
dtype: int64

# Checking out how many missing values are there?

In [70]:
total_cells = np.product(df.shape)      ##### Almost a quarter of the cells in this dataset are empty! In the next step,
total_missing = missing_values_count.sum() #### we're going to take a closer look at some of the columns with missing values 
(total_missing/total_cells) * 100         #### and try to figure out what might be going on with them.

26.26002315058403

In [71]:
missing_values_count[0:10]

Permit Number                  0
Permit Type                    0
Permit Type Definition         0
Permit Creation Date           0
Block                          0
Lot                            0
Street Number                  0
Street Number Suffix      196684
Street Name                    0
Street Suffix               2768
dtype: int64

# Remove all the rows that contain a missing value

In [72]:
df.dropna()

Empty DataFrame
Columns: [Permit Number, Permit Type, Permit Type Definition, Permit Creation Date, Block, Lot, Street Number, Street Number Suffix, Street Name, Street Suffix, Unit, Unit Suffix, Description, Current Status, Current Status Date, Filed Date, Issued Date, Completed Date, First Construction Document Date, Structural Notification, Number of Existing Stories, Number of Proposed Stories, Voluntary Soft-Story Retrofit, Fire Only Permit, Permit Expiration Date, Estimated Cost, Revised Cost, Existing Use, Existing Units, Proposed Use, Proposed Units, Plansets, TIDF Compliance, Existing Construction Type, Existing Construction Type Description, Proposed Construction Type, Proposed Construction Type Description, Site Permit, Supervisor District, Neighborhoods - Analysis Boundaries, Zipcode, Location, Record ID]
Index: []

[0 rows x 43 columns]

# Remove all columns with at least one missing value

In [73]:
columns_with_na_dropped = df.dropna(axis=1)
columns_with_na_dropped.head()

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Name,Current Status,Current Status Date,Filed Date,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,Ellis,expired,12/21/2017,05/06/2015,1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,Geary,issued,08/03/2017,04/19/2016,1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,Pacific,withdrawn,09/26/2017,05/27/2016,1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,Pacific,complete,07/24/2017,11/07/2016,1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,Market,issued,12/01/2017,11/28/2016,144548169992

# Checking how much data did we lose

In [74]:
print("Columns in original dataset: %d \n" % df.shape[1])
print("Columns with na's dropped: %d" % columns_with_na_dropped.shape[1])

Columns in original dataset: 43

Columns with na's dropped: 12

# Get a small subset of the Building permits dataset

In [75]:
df = df.loc[:, 'Permit Number':'Record ID'].head()
df

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992

# Replacing all NA's with 0

In [76]:
df.fillna(0)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,0,Ellis,St,...,3.0,constr type 3,0.0,0,0,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,0,Geary,St,...,3.0,constr type 3,0.0,0,0,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,0,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,0,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,0,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),0,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,0,Market,St,...,3.0,constr type 3,0.0,0,0,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992

In [77]:
df.fillna(method = 'bfill', axis=0).fillna(0)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,0.0,Ellis,St,...,3.0,constr type 3,1.0,constr type 1,0.0,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,0.0,Geary,St,...,3.0,constr type 3,1.0,constr type 1,0.0,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,0.0,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,0.0,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,0.0,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),0.0,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,0.0,Market,St,...,3.0,constr type 3,0.0,0,0.0,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992